### ISSUE TITLE
Update Sequelize operators [Security]

### ISSUE THREAD

**Issue by jesterswilde** [jonathanhawleypeters/magic-search#10]
In a new version of Sequelize they updated from using $ne, $or and the like to using [Op.ne] (pulled off of Sequelize.Op) 

This format is better for security reasons.  We should switch to this version of doing things.

**Comment by jonathanhawleypeters** [comment]
If what you say is true, yes. ASAP.

**Comment by jesterswilde** [comment]
Completed change.
