### ISSUE TITLE
Sets are unsupported

### ISSUE THREAD

**Issue by jonathanhawleypeters** [jonathanhawleypeters/magic-search#20]
Considerations:
1. They need their own table like Types and Subtypes, joined upon query
2. They will allow us to support card art variations
3. When querying, they will likely act as a global filter

**Comment by jesterswilde** [comment]
@jonathanhawleypeters  Closing this. Each card only has one set now. Not all functionality is implemented yet for search, but these will be handled just the same as everything else.
